### ISSUE TITLE
Add some contacts

### ISSUE THREAD

**Issue by halofourteen** [Earthmor/xmatic#1]
Sup bru!
Please add some contacts to my profile! 

- My sooper-dooper instagram `https://www.instagram.com/halofourteen/` with fa-icon `https://fontawesome.com/icons/instagram?style=brands`
- My one and the only Meduim `https://medium.com/@halo` with fa-icon `https://fontawesome.com/icons/medium?style=brands`
- And the last but not least, ultra-modern ello profile `https://ello.co/halo14` with custom icon from fa, cuz there's no branded icon in theirs icon set `https://fontawesome.com/icons/smile?style=solid`

**Comment by wilirys** [comment]
completed!
